name: Manual Release
on:
  workflow_dispatch

jobs:
  assemble_release:

    name: Assemble Release Apk
    runs-on: macos-10.15

    steps:
      - name: CheckOut Current Branch
        uses: actions/checkout@v2

      - name: Install Java 11 SDK for Gradle
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Decode Key
        id: write_file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'app_github_keystore.jks'
          fileDir: app/build/outputs/apk/release
          encodedString: ${{ secrets.KEY_BASE_64 }}

      - run: echo storeFile = ${{secrets.KEY_STORE_PATH}} >> local.properties
      - run: echo alias = ${{secrets.KEY_ALIAS}} >> local.properties
      - run: echo keyPassword = ${{secrets.KEY_ALIAS_PASS}} >> local.properties
      - run: echo storePassword = ${{secrets.KEYSTORE_PASS}} >> local.properties

      - name: Clean Project
        run: ./gradlew clean

      - name: Assemble Release App
        run : ./gradlew assembleRelease

      #- name: Sign Apk
      #  uses: r0adkll/sign-android-release@v1
      #  id: sign_app
      #  with:
      #    releaseDirectory: app/build/outputs/apk/release
      #    signingKeyBase64: ${{secrets.KEY_BASE_64}}
      #    alias: ${{ secrets.KEY_ALIAS }}
      #    keyStorePassword: ${{ secrets.KEYSTORE_PASS }}
      #    keyPassword: ${{ secrets.KEY_ALIAS_PASS }}


      - name: Upload JKS
        uses: actions/upload-artifact@v2
        with:
          name: Signed APK
          path: app/build/outputs/apk/release

      #- name: Upload Signing APK
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: Signed APK
      #    path: ${{steps.sign_app.outputs.signedReleaseFile}}
#



