name: Manual Release
on:
  workflow_dispatch

jobs:
  assemble_release:
    name: Assemble Release Apk
    runs-on: macos-10.15

    steps:
      - name: CheckOut Current Branch
        uses: actions/checkout@v2

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Assemble Release App
        run : ./gradlew assembleRelease



