name: Manual Release
on:
  workflow_dispatch

jobs:
  assemble_release:
    name: Assemble Release Apk
    runs-on: macos-10.15

    steps:
      - name: CheckOut Current Branch
        uses: actions/checkout@v2

      - name: Install Java 11 SDK for Gradle
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Assemble Release App
        run : ./gradlew assembleRelease



